// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package solubris.mon4roo.core;

import org.springframework.beans.factory.annotation.Configurable;
import solubris.mon4roo.core.MonitorMetricIntegrationTest;

privileged aspect MonitorMetricIntegrationTest_Roo_Configurable {
    
    declare @type: MonitorMetricIntegrationTest: @Configurable;
    
}
